import type { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import { Categories, PostCard, PostWidget } from "../components";
import { Post } from "../models/Post";
import FeaturedPostsCarousel from "../sections/FeaturedPostsCarousel";
import { fetchPosts } from "../services";

type Props = {
  posts: { node: Post }[];
};

const Home: NextPage<Props> = ({ posts }) => {
  return (
    <main className="container mx-auto px-10 mb-8">
      <Head>
        <title>Sample Next.js Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <FeaturedPostsCarousel />
      <section className="grid grid-cols-1 lg:grid-cols-12 gap-12">
        <ul className="lg:col-span-8 col-span-1">
          {posts.map((post, idx) => (
            <li key={idx}>
              <PostCard {...post} />
            </li>
          ))}
        </ul>
        <section className="lg:col-span-4 col-span-1">
          <ul className="lg:sticky relative top-8">
            <PostWidget />
            <Categories />
          </ul>
        </section>
      </section>
    </main>
  );
};

export const getStaticProps: GetStaticProps = async () => {
  const posts = (await fetchPosts()) || [];

  return {
    props: {
      posts,
    },
  };
};

export default Home;
